id: PDF0D19BE
initial_creation_type: input
source_metadata:
  title: 'MSV 1,04: Varṣāvastu'
  language: bo
  volumes:
    6996b545b6164a4e915d817357eb2b49:
      title: Piṇḍoddāna
      base_file: Piṇḍoddāna.txt
      work_id: W741254F0
    5678819b979445b2b427b15847a66eb9:
      title: Uddāna 1
      base_file: Uddāna 1.txt
      work_id: WC65A614A
    856e239a9dea4754b98c4ff866b56351:
      title: Uddāna 2
      base_file: Uddāna 2.txt
      work_id: W72E44483
    acbe8cb0f4f44fdaa23ae3c47e1e609f:
      title: Uddāna 3
      base_file: Uddāna 3.txt
      work_id: W50119903
  chapter_to_tile: {}
created_at: '2022-03-01T22:15:06.709439'
last_modified_at: '2022-03-01T22:15:06.709466'
